version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask
